# CADASTRA CLIENTE
# ABA_1 - DADOS CADASTRAIS
# CODIGO CLIENTE: INCREMENTAL
#  NOME DO CLIENTE
# PES FIS/JUR
# N FANTASIA
# CEP
# ENDERECO
# NUMERO
# COMPLEMENTO
# BAIRRO
# CIDADE
# COD MUNICIPIO
# ESTADO
# TELEFONES
# EMAIL
# OBSERVACOES
# ATIVO (S/N)
# OBSERVAÇÃO

# ABA_2 ADM/FIN
# TIPO FRETE (CIF/FOB)
# VENDEDOR
# BANCO (FINANCEIRO)
# MAIOR COMPRA
# MAIOR, MENOR E MÉDIA (ATRASO, VALOR NF)
# NUMERO DE COMPRAS
# OBSERVAÇÃO

# ABA_3 VENDAS
# COND_PAGAMENTO (FINANCEIRO)
# LEADTIME (LOGISTICA)
# TRANSPORTADOR (LOGISTICA)
# OBSERVAÇÃO

# INSERE PEDIDO DE VENDAS
#
# RELATORIO DE PEDIDOS DE VENDAS. COM POSSIBILIDADE DE EDITAR, CASO O PEDIDO AINDA NÃO TENHA SIDO SEPARADO
from flask import render_template
from forms import Mod_Logistica
