# COMO CALCULAR OS IMPOSTOS NA VENDA DE UM PRODUTO PARA A EMISSAO DA NOTA FISCAL





# COMO CALCULAR O PIS E COFINS
# COMO CALCULAR O IPI E ICMS
# COMO CALCULAR O PIS E COFINS
# FÓRMULA: (VALOR DA OPERAÇÃO x ALIQUOTA) / 100
# EXEMPLO: (R$ 100,00 x 07%) / 100 = R$ 7,00
# ICMS DOS ESTADOS DO BRASIL

