from flask import render_template
from forms import Mod_Logistica
from geral import Formatadores
# CADASTRA TABELA DE PRECOS DE VENDAS
# DIV 1
# COD DA TABELA: INCREMENTAL
# DESCRIÇÃO DA TABELA
# TABELA ATIVA (S/N)
# VIGÊNCIA DA TABELA: DATA INICIAL E DATA FINAL, HORA INICIAL E HORA FINAL

# DIV 2

# CODIGO, DESCRIÇÃO, PREÇO DE VENDA, ITEM ATIVO (S/N), ESTADO(UF) DE VIGÊNCIA,
# OPÇÃO DE CRIAR, COPIAR EDITAR E DELETAR TABELA,
# OPÇÃO DE CRIAR, EDITAR E DELETAR ITEM DA TABELA



#