import mysql.connector

def acesso_db():

    mydb = mysql.connector.connect(
        host="localhost", user="root", password="Ma204619@", database="projeto_erp"
    )
    connect = mydb.connect()
    mycursor = mydb.cursor()
    return mydb, mycursor, connect


mydb, mycursor, connect = acesso_db()

"""
INSERT INTO FORNECEDORES (DATA, CODIGO, NOMEFANTASIA, RAZAOSOCIAL, CNPJ, INSCRICAOESTADUAL, EMAIL, TELEFONE, CEP, ENDERECO, MUNICIPIO, UF)
INSERT INTO PRODUTOS (DATA, CODIGO, FORNECEDOR, EAN, DESCRICAO, UNIDADE, CATEGORIA, VALOR, USUARIO)
INSERT INTO ORDEM_COMPRA (DATA, ORDEM_COMPRA, ITEM, DESCRICAO, UNIDADE, CATEGORIA, CODIGO, EAN, QUANTIDADE, PRECO, TOTAL_ITEM, SALDO_QTD,"SALDO_TOTAL_ITEM, STATUS,USUARIO)

INSERT INTO CLIENTES(DATA,CODIGO,RAZAO_SOCIAL,CNPJ,INSCRICAO_ESTADUAL,EMAIL,CEP, TELEFONE,ENDERECO,MUNICIPIO,UF,TABELA,USUARIO);
INSERT INTO ORDEM_VENDA (DATA ORDEM_VENDA, ITEM, CODIGO_PRODUTO, FORNECEDOR, DESCRICAO, EAN, UN, TABELA, PRECO_LISTA, PRECO_VENDA, QUANTIDADE, ACRESC_DESC, TOTAL_PEDIDO, USUARIO, STATUS_PEDIDO, COD_CLIENTE, CLIENTE);
INSERT INTO PRECIFICACAO(DATA, EAN, VALOR, MARGEM, CUSTOS, ACRESCIMO, DESCONTO, PRECOVENDA, USUARIO);

INSERT INTO ESTOQUE (DATA, TIPO_MOV, ORDEM_COMPRA, NOTA_FISCAL, EAN, CODIGO, DESCRICAO, QUANTIDADE, VALOR, USUARIO);
"""

